/**
 * Executive briefing generator (README.md).
 * Produces a 1-page briefing: scope, key stats, top findings with dollar values,
 * what it means, and next steps.
 */
import type {
  InvestigationParams,
  MaterialFinding,
  QueryContext,
  Severity,
} from "../shared/types.js";

export interface BriefingInput {
  findings: MaterialFinding[];
  params: InvestigationParams;
  queryContext?: QueryContext;
  totalAwards: number;
  totalSignals: number;
  rerunCommand?: string;
}

/**
 * Generate a concise executive briefing in Markdown.
 */
export function generateBriefing(input: BriefingInput): string {
  const { findings, params, queryContext, totalAwards, totalSignals } = input;
  const lines: string[] = [];

  // ─── Title ─────────────────────────────────────────────────────────────
  const title = params.recipient
    ? `${params.agency ?? "All Agencies"} → ${params.recipient}`
    : params.agency ?? "Investigation";

  lines.push(`# Procurement Investigation: ${title}`);
  lines.push("");
  lines.push(`**Period:** ${params.periodStart} to ${params.periodEnd}`);
  lines.push(`**Generated:** ${new Date().toISOString().slice(0, 10)}`);
  lines.push("");

  // ─── Disclaimer ────────────────────────────────────────────────────────
  lines.push("> Red flags are screening indicators, **not proof of wrongdoing**.");
  lines.push("> See case.md for full methodology and data quality notes.");
  lines.push("");

  // ─── Key Stats ─────────────────────────────────────────────────────────
  lines.push("## At a Glance");
  lines.push("");
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Awards Analyzed | ${totalAwards.toLocaleString()} |`);
  lines.push(`| Signals Detected | ${totalSignals.toLocaleString()} |`);
  lines.push(`| Material Findings | ${findings.length} |`);

  if (findings.length > 0) {
    const totalExposure = findings.reduce((sum, f) => sum + f.totalDollarValue, 0);
    const highCount = findings.filter((f) => f.severity === "high").length;
    lines.push(`| High Severity Findings | ${highCount} |`);
    lines.push(`| Total Dollar Exposure | $${totalExposure.toLocaleString()} |`);
  }

  lines.push("");

  // ─── Top Findings ──────────────────────────────────────────────────────
  if (findings.length > 0) {
    const topFindings = findings.slice(0, 5);
    lines.push("## Top Findings");
    lines.push("");

    for (const finding of topFindings) {
      const severityIcon = severityLabel(finding.severity);
      lines.push(
        `### ${severityIcon} ${finding.indicatorName} — ${finding.entityName}`,
      );
      lines.push("");

      if (finding.fiveCs) {
        lines.push(`**What:** ${finding.fiveCs.condition}`);
        lines.push("");
        lines.push(`**Standard:** ${finding.fiveCs.criteria}`);
        lines.push("");
        lines.push(`**Impact:** ${finding.fiveCs.effect}`);
        lines.push("");
      } else {
        lines.push(finding.signals[0]?.context ?? "");
        lines.push("");
      }

      lines.push(
        `*${finding.affectedAwardIds.length} awards, ` +
        `$${finding.totalDollarValue.toLocaleString()} total value*`,
      );

      // AI tag
      if (finding.aiTag) {
        lines.push(`\`[${finding.aiTag}]\``);
      }
      lines.push("");
    }
  } else {
    lines.push("## Findings");
    lines.push("");
    lines.push("No material findings exceeded the configured thresholds.");
    lines.push("");
  }

  // ─── Next Steps ────────────────────────────────────────────────────────
  lines.push("## Next Steps");
  lines.push("");
  lines.push(generateNextSteps(findings, params, queryContext));
  lines.push("");

  // ─── Files in this folder ──────────────────────────────────────────────
  lines.push("## Files in This Case Folder");
  lines.push("");
  lines.push("| File | Description |");
  lines.push("|------|-------------|");
  lines.push("| `case.md` | Full investigation report with all signals and hypotheses |");
  lines.push("| `dashboard.html` | Interactive HTML dashboard with charts |");
  lines.push("| `evidence/` | CSV evidence tables and SVG charts |");
  lines.push("| `data/` | Raw JSON data files (awards, signals, hypotheses) |");
  lines.push("| `provenance.json` | Run metadata and audit trail |");
  lines.push("");

  lines.push("---");
  lines.push("*Generated by [Procurement Investigator](https://github.com/) (Investigation-as-Code)*");

  return lines.join("\n");
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function severityLabel(severity: Severity): string {
  switch (severity) {
    case "high": return "[HIGH]";
    case "medium": return "[MEDIUM]";
    case "low": return "[LOW]";
  }
}

function generateNextSteps(
  findings: MaterialFinding[],
  params: InvestigationParams,
  queryContext?: QueryContext,
): string {
  const steps: string[] = [];

  // Per-finding next steps
  const indicatorActions: Record<string, string> = {
    R001: "Review solicitation practices and advertisement reach for single-bid awards",
    R002: "Verify sole-source justifications (J&A documents) for top non-competitive awards",
    R003: "Examine whether near-threshold awards represent split requirements",
    R004: "Check SAM.gov entity type (FFRDC/UARC) and assess vendor diversification",
    R005: "Review modification history and compare original vs. current scope",
    R006: "Compare prices with similar procurements from other agencies",
  };

  const seenIndicators = new Set<string>();
  for (const finding of findings.slice(0, 5)) {
    if (!seenIndicators.has(finding.indicatorId)) {
      seenIndicators.add(finding.indicatorId);
      const action = indicatorActions[finding.indicatorId];
      if (action) {
        steps.push(`- **${finding.indicatorId}:** ${action}`);
      }
    }
  }

  // Suggest scope adjustments
  if (queryContext?.isRecipientFiltered) {
    steps.push(`- Run without \`--recipient\` to see the full agency portfolio`);
  }
  if (!queryContext?.isRecipientFiltered && params.agency) {
    steps.push(`- Add \`--recipient\` to focus on a specific entity`);
  }

  // Deep investigation
  steps.push(`- Run with \`--deep\` to enable Opus 4.6 investigative agent`);

  if (steps.length === 0) {
    return "No specific follow-up actions identified. The dataset appears within normal parameters.";
  }

  return steps.join("\n");
}
