/**
 * Investigation narrative renderer.
 * Converts InvestigationStep[] and agent findings into readable Markdown.
 */
import type { InvestigationNarrative, InvestigationStep, MaterialFinding } from "../shared/types.js";

/**
 * Render an investigation narrative as Markdown for investigation-narrative.md.
 */
export function renderNarrative(narrative: InvestigationNarrative): string {
  const lines: string[] = [];

  lines.push("# Investigation Narrative");
  lines.push("");
  lines.push("> This document records the reasoning process of the Opus 4.6 investigative agent.");
  lines.push("> Each step shows the agent's analytical thinking as it examined the procurement data.");
  lines.push("");

  // ─── Reasoning Steps ──────────────────────────────────────────────────
  if (narrative.steps.length > 0) {
    lines.push("## Reasoning Trace");
    lines.push("");

    for (let i = 0; i < narrative.steps.length; i++) {
      const step = narrative.steps[i];
      lines.push(`### Step ${i + 1}: ${phaseLabel(step.phase)}`);
      lines.push(`*${step.timestamp}*`);
      lines.push("");
      lines.push(step.reasoning);
      lines.push("");

      if (step.relatedSignals && step.relatedSignals.length > 0) {
        lines.push(`**Related signals:** ${step.relatedSignals.map((s) => `\`${s}\``).join(", ")}`);
      }
      if (step.relatedEntities && step.relatedEntities.length > 0) {
        lines.push(`**Related entities:** ${step.relatedEntities.join(", ")}`);
      }
      if (step.relatedSignals?.length || step.relatedEntities?.length) {
        lines.push("");
      }
    }
  }

  // ─── Agent-Created Findings ────────────────────────────────────────────
  if (narrative.agentFindings.length > 0) {
    lines.push("## Agent-Discovered Findings");
    lines.push("");
    lines.push("The following findings were created by the investigative agent based on");
    lines.push("its analysis of enrichment data and cross-references:");
    lines.push("");

    for (const finding of narrative.agentFindings) {
      lines.push(`### ${finding.id}: ${finding.indicatorName} — ${finding.entityName}`);
      lines.push(`**Severity:** ${finding.severity} | **Source:** \`[AI-DISCOVERED]\``);
      lines.push("");

      if (finding.fiveCs) {
        lines.push("| Component | Detail |");
        lines.push("|-----------|--------|");
        lines.push(`| **Condition** | ${finding.fiveCs.condition} |`);
        lines.push(`| **Criteria** | ${finding.fiveCs.criteria} |`);
        lines.push(`| **Cause** | ${finding.fiveCs.cause} |`);
        lines.push(`| **Effect** | ${finding.fiveCs.effect} |`);
        lines.push(`| **Recommendation** | ${finding.fiveCs.recommendation} |`);
        lines.push("");
      }
    }
  }

  lines.push("---");
  lines.push("*Generated by Procurement Investigator — Opus 4.6 Investigative Agent*");

  return lines.join("\n");
}

function phaseLabel(phase: InvestigationStep["phase"]): string {
  switch (phase) {
    case "hypothesis": return "Forming Hypothesis";
    case "data_gathering": return "Gathering Data";
    case "analysis": return "Analyzing Results";
    case "synthesis": return "Synthesizing Findings";
  }
}
